### ISSUE TITLE
CKDatabaseOperations must be submitted to a CKDatabase

### ISSUE THREAD

**Issue by kenton7** [caiyue1993/IceCream#246] opened 2021-09-01 10:55 UTC
When launching the app, it crashes with the error "CKDatabaseOperations must be submitted to a CKDatabase". It all started with iOS 15 beta 4. It is now beta 8 and the bug still persists. When I turn off sync with iCloud in the settings of my app, everything works correctly.
*** Terminating app due to uncaught exception 'CKException', reason: 'CKDatabaseOperations must be submitted to a CKDatabase'
terminating with uncaught exception of type CKException

**Comment by caiyue1993** [comment] 2021-09-01 15:22
Duplicate of #246. Please turn to that issue. Thanks.

**Closed by caiyue1993** 2021-09-01 15:22 UTC
Labels: duplicate
