### ISSUE TITLE
How detect changes after remote push with CloudKit?

### ISSUE THREAD

**Issue by ivanvorobei** [caiyue1993/IceCream#161] opened 2019-08-19 10:43 UTC
Hi! Thanks for `IceCream`, it magic! 
This code post notification, but if add other observer realm not updated yet. 

```swift
if let dict = userInfo as? [String: NSObject], let notification = CKNotification(fromRemoteNotificationDictionary: dict), let subscriptionID = notification.subscriptionID, IceCreamSubscription.allIDs.contains(subscriptionID) {
            
   NotificationCenter.default.post(name: Notifications.cloudKitDataDidChangeRemotely.name, object: nil, userInfo: userInfo)
            completionHandler(.newData)
}
```

Need method after complete update realm. It available?

**Comment by caiyue1993** [comment] 2019-10-04 14:43
Duplicate of #152

**Closed by caiyue1993** 2019-10-04 14:43 UTC
Labels: duplicate
